### PR TITLE
New version with drop list filter

### PR DESCRIPTION
**Pull request by intika**

### CODE REVIEW

**Comment by liudongmiao** [comment]
Thanks. But I won't accept this pull request.

1). this pull request will discards other type of search, like name match and package name match
2). type filter is a lower frequency function, and actually, I don't suggest to use it. The default should be ok for most users. (default for all application is "-3g", and for prevent list is "", means all).

There are chinese guys implemented this too, I didn't accept.

**Comment by intika** [comment]
The classic search bar is still there just bellow the drop menu and we still could search with package name and application name

**Comment by intika** [comment]
but i get your point... you want somehow to keep the application as simple as possible and you are right :+1:

**Comment by liudongmiao** [comment]
KISS: keep it simple, stupid.

**Pull request closed without merging**
